### ISSUE TITLE
Attractiveness of Stackchainers

### ISSUE THREAD

**Issue by von-Hodl** [stackchainsats/stackchain#13]
I've noticed Stackchainers are more attractive then average and I think it's an issue that needs to be addressed.

**Comment by PsyduckSpyduck** [comment]
What solution do you propose?

**Comment by von-Hodl** [comment]
Perhaps a cream?

**Comment by PsyduckSpyduck** [comment]
> 

A cream is the obvious solution but I've tried many so far and have yet to find a promising candidate.
